---
layout: post
title:  "Promise学习笔记"
categories: JavaScript
---


## Promise简介

- Promise是一种编写异步处理的规则

### 创建实例

```
var promise = new Promise(function(resolve, reject) {
    // 异步处理
    // 处理结束后、调用resolve 或 reject
});
```

### 实例的方法

- 成功时，执行onFulfilled
- 失败时，执行onRejected

```
promise.then(onFulfilled, onRejected)
```

失败时的操作

```
promise.catch(onRejected)
```

### Promise的工作流程

```
function asyncFunction(){
  return new Promise(function (resolve, reject){
    setTimeout(function(){
      resolve("Async Hello World!");
    },16)
  })
}

asyncFunction().then(function(value){
  console.log(value); // => 'Async Hello world'
}).catch(function(error){
  console.log(error);
})
```

### Promise的工作状态

用new Promise实例化的Promise对象有以下三种状态

- Fulfilled：成功
- Rejected：失败
- Pending：初始态

resolve(value)会将promise对象变为resolve状态，同时使用value作为参数调用onFulfilled函数

## Promise实战

### resolve

- resolve是new Promise()的快捷方式

静态方法Promise.resolve(value) 可以认为是 new Promise() 方法的快捷方式。

比如：Promise.resolve(42); ===

```
new Promise(function(resolve){
    resolve(42);
});
```

同时Promise返回的也是一个promise对象，还可以接着进行then()调用

- thenable

就像具有.length方法的非数组对象被成为Array like一样
thenable指的是一个具有.then方法的对象


将thenable对象转换为promise对象要求thenable对象所拥有的 then 方法应该和Promise所拥有的 then 方法具有同样的功能和处理过程

通过Promise.resolve( thenable object)可以把一个thenable对象转化为Promise对象


## reject
Promise.reject(new Error("出错了"))  == 

```
new Promise(function(resolve,reject){
    reject(new Error("出错了"));
});
```

调用该promise对象通过then指定的 onRejected 函数，并将错误（Error）对象传递给这个 onRejected 函数

## 异步

then是一种异步操作，

## Promise chain

链式调用时，reject能够捕获前面的then发生的异常

链式调用时，上一个then的返回值能够传递给下一个then，因为每个then返回的都是一个Promise对象

## catch

Promise.catch == 

```
promise.then(undefined, onRejected); 
```

IE8-版本的浏览器中，使用Promise.catch会出现错误：identifier not found . 因为ECMAScript3中，catch作为保留字，不能作为属性来使用。ECMAScript5中可以。
但是，可以通过“中括号标记法”来使用：

```
promise["catch"](function (error) {
    console.error(error);
});
```

## 新的Promise对象

每一次调用then都会返回一个<b>新的</b>Promise对象。

所以尽量使用链式调用来避免惯性思维造成的错误。